<?php

declare(strict_types=1);

namespace App\Service\User;

use App\Entity\User;
use Psr\Log\LoggerInterface;

final readonly class CoachInsightService
{
    private const LOCAL_FALLBACK_CACHE_TTL_SECONDS = 300;

    public function __construct(
        private PerformanceReportBuilder $reportBuilder,
        private CoachCacheService $cacheService,
        private GeminiClient $geminiClient,
        private LoggerInterface $logger,
    ) {
    }

    /**
     * @return array{
     *     report:array<string,mixed>,
     *     insight:array{
     *         summary:string,
     *         strengths:list<string>,
     *         improvements:list<string>,
     *         recommendations:list<string>,
     *         plan7Days:list<string>,
     *         nutritionSupport:array{
     *             focus:string,
     *             foods:list<string>,
     *             dishes:list<string>,
     *             note:string
     *         },
     *         tone:string,
     *         source:string
     *     },
     *     reportHash:string
     * }
     */
    public function getInsight(User $user): array
    {
        $this->logger->info('Coach insight generation starts.', [
            'user_id' => $user->getId(),
        ]);

        $report = $this->reportBuilder->build($user);
        $reportHash = $this->cacheService->hashReport($report);

        $this->logger->info('Coach insight cache is being checked.', [
            'user_id' => $user->getId(),
            'report_hash' => $reportHash,
        ]);

        $cachedInsight = $this->cacheService->get($reportHash);

        if (is_array($cachedInsight) && ($cachedInsight['source'] ?? null) === 'ai') {
            $this->logger->info('Coach insight AI cache is being used.', [
                'user_id' => $user->getId(),
                'report_hash' => $reportHash,
            ]);

            return [
                'report' => $report,
                'insight' => $this->normalizeCachedInsight($cachedInsight),
                'reportHash' => $reportHash,
            ];
        }

        if (is_array($cachedInsight) && ($cachedInsight['source'] ?? null) === 'local') {
            if ($this->isLocalFallbackCacheUsable($cachedInsight)) {
                $this->logger->info('Coach insight local fallback cache is being used.', [
                    'user_id' => $user->getId(),
                    'report_hash' => $reportHash,
                    'retry_after' => $cachedInsight['retryAfter'] ?? null,
                ]);

                return [
                    'report' => $report,
                    'insight' => $this->normalizeCachedInsight($cachedInsight),
                    'reportHash' => $reportHash,
                ];
            }

            $this->logger->info('Coach insight cached local fallback expired; Gemini retry is being attempted.', [
                'user_id' => $user->getId(),
                'report_hash' => $reportHash,
                'retry_after' => $cachedInsight['retryAfter'] ?? null,
            ]);
        } else {
            $this->logger->info('Coach insight cache miss; Gemini is about to be called.', [
                'user_id' => $user->getId(),
                'report_hash' => $reportHash,
            ]);
        }

        $this->logger->info('Coach insight Gemini call is about to start.', [
            'user_id' => $user->getId(),
            'report_hash' => $reportHash,
        ]);

        $insight = $this->geminiClient->generateCoachInsight($report);
        if ($insight !== null) {
            $this->logger->info('Coach insight generated by Gemini.', [
                'user_id' => $user->getId(),
                'report_hash' => $reportHash,
            ]);

            $this->cacheService->save($reportHash, $insight);

            return [
                'report' => $report,
                'insight' => $insight,
                'reportHash' => $reportHash,
            ];
        }

        $this->logger->info('Coach insight using local fallback', [
            'user_id' => $user->getId(),
            'report_hash' => $reportHash,
        ]);

        $fallback = $this->withFallbackCacheMetadata($this->localFallback($report));
        $this->logger->info('Coach insight local fallback regenerated.', [
            'user_id' => $user->getId(),
            'report_hash' => $reportHash,
            'retry_after' => $fallback['retryAfter'],
        ]);
        $this->cacheService->save($reportHash, $fallback, self::LOCAL_FALLBACK_CACHE_TTL_SECONDS);

        return [
            'report' => $report,
            'insight' => $fallback,
            'reportHash' => $reportHash,
        ];
    }

    /**
     * @param array<string,mixed> $report
     * @return array{
     *     summary:string,
     *     strengths:list<string>,
     *     improvements:list<string>,
     *     recommendations:list<string>,
     *     plan7Days:list<string>,
     *     nutritionSupport:array{
     *         focus:string,
     *         foods:list<string>,
     *         dishes:list<string>,
     *         note:string
     *     },
     *     tone:string,
     *     source:string
     * }
     */
    private function localFallback(array $report): array
    {
        $engagementScore = (int) ($report['engagementScore'] ?? 0);
        $streakDays = (int) ($report['streakDays'] ?? 0);
        $completionRate = (int) ($report['completionRate'] ?? 0);
        $activeMinutes = (int) ($report['activeMinutesLast7Days'] ?? 0);
        $bestMoment = (string) ($report['bestMoment'] ?? 'a calm moment');
        $consistency = (string) ($report['consistencyLevel'] ?? 'Building');
        $mostCompleted = (string) ($report['mostCompletedExercise'] ?? 'your preferred exercise');

        return [
            'summary' => sprintf(
                'Your current exercise rhythm is %s, with an engagement score of %d/100 and %d active minutes in the last 7 days.',
                strtolower($consistency),
                $engagementScore,
                $activeMinutes,
            ),
            'strengths' => [
                $streakDays > 0 ? sprintf('You have built a %d-day completion streak.', $streakDays) : 'You have already started building exercise awareness.',
                $completionRate >= 60 ? sprintf('Your completion rate is steady at %d%%.', $completionRate) : sprintf('You have completed %d sessions so far.', (int) ($report['completedSessions'] ?? 0)),
            ],
            'improvements' => [
                $activeMinutes < 30 ? 'Add a few short sessions this week to grow your active minutes gently.' : 'Keep spreading your active minutes across the week.',
                $completionRate < 70 ? 'Choose shorter sessions when your energy is low so completion feels easier.' : 'Maintain your current completion rhythm without pushing too hard.',
            ],
            'recommendations' => [
                sprintf('Use %s as your anchor time when possible.', $bestMoment),
                sprintf('Repeat %s when you need a familiar reset.', $mostCompleted),
                'Treat consistency as the goal: small completed sessions matter more than perfect sessions.',
            ],
            'plan7Days' => [
                'Day 1: Complete one short grounding or breathing session.',
                'Day 2: Repeat a familiar exercise and notice how your energy changes.',
                'Day 3: Try a session at your best moment of the day.',
                'Day 4: Keep it light with a low-pressure relaxation exercise.',
                'Day 5: Add one focused session and write a short reflection after it.',
                'Day 6: Return to your most completed exercise for confidence.',
                'Day 7: Review your week and choose one habit to carry forward.',
            ],
            'nutritionSupport' => $this->localNutritionSupport($report),
            'tone' => 'supportive',
            'source' => 'local',
        ];
    }

    /**
     * @param array<string,mixed> $insight
     * @return array{
     *     summary:string,
     *     strengths:list<string>,
     *     improvements:list<string>,
     *     recommendations:list<string>,
     *     plan7Days:list<string>,
     *     nutritionSupport:array{
     *         focus:string,
     *         foods:list<string>,
     *         dishes:list<string>,
     *         note:string
     *     },
     *     tone:string,
     *     source:string
     * }
     */
    private function normalizeCachedInsight(array $insight): array
    {
        return [
            'summary' => is_string($insight['summary'] ?? null) ? $insight['summary'] : 'Your coach insight is ready.',
            'strengths' => $this->listValue($insight['strengths'] ?? null),
            'improvements' => $this->listValue($insight['improvements'] ?? null),
            'recommendations' => $this->listValue($insight['recommendations'] ?? null),
            'plan7Days' => array_slice($this->listValue($insight['plan7Days'] ?? null), 0, 7),
            'nutritionSupport' => $this->normalizeNutritionSupport($insight['nutritionSupport'] ?? null),
            'tone' => 'supportive',
            'source' => ($insight['source'] ?? null) === 'ai' ? 'ai' : 'local',
        ];
    }

    /** @param array<string,mixed> $insight */
    private function isLocalFallbackCacheUsable(array $insight): bool
    {
        $retryAfter = $insight['retryAfter'] ?? null;
        if (!is_string($retryAfter) || trim($retryAfter) === '') {
            return false;
        }

        try {
            return new \DateTimeImmutable($retryAfter) > new \DateTimeImmutable();
        } catch (\Throwable) {
            return false;
        }
    }

    /**
     * @param array<string,mixed> $fallback
     * @return array<string,mixed>
     */
    private function withFallbackCacheMetadata(array $fallback): array
    {
        $now = new \DateTimeImmutable();

        return [
            ...$fallback,
            'source' => 'local',
            'cachedAt' => $now->format(\DateTimeInterface::ATOM),
            'retryAfter' => $now->modify(sprintf('+%d seconds', self::LOCAL_FALLBACK_CACHE_TTL_SECONDS))->format(\DateTimeInterface::ATOM),
        ];
    }

    /**
     * @param array<string,mixed> $report
     * @return array{
     *     focus:string,
     *     foods:list<string>,
     *     dishes:list<string>,
     *     note:string
     * }
     */
    private function localNutritionSupport(array $report): array
    {
        $activeMinutes = (int) ($report['activeMinutesLast7Days'] ?? 0);
        $completionRate = (int) ($report['completionRate'] ?? 0);
        $bestMoment = strtolower((string) ($report['bestMoment'] ?? ''));
        $favoriteTypes = is_array($report['favoriteTypes'] ?? null) ? $report['favoriteTypes'] : [];
        $favoriteText = strtolower(implode(' ', array_map(static fn(mixed $item): string => is_string($item) ? $item : '', $favoriteTypes)));

        if (str_contains($bestMoment, 'evening') || str_contains($favoriteText, 'relax')) {
            return [
                'focus' => 'Evening-friendly nourishment that supports calm routines and steady recovery.',
                'foods' => ['yogurt', 'oats', 'bananas', 'nuts'],
                'dishes' => ['Yogurt with oats and banana', 'Chickpea salad with leafy greens'],
                'note' => 'If tiredness stays high over time, iron, B12, folate, or vitamin D may be worth discussing with a healthcare professional.',
            ];
        }

        if ($activeMinutes < 30 || $completionRate < 60) {
            return [
                'focus' => 'Simple energy-supporting meals that are easy to keep consistent.',
                'foods' => ['eggs', 'lentils', 'spinach', 'chickpeas'],
                'dishes' => ['Lentil and spinach soup', 'Egg and avocado toast'],
                'note' => 'Focus on regular meals and energy-supporting foods before considering supplements.',
            ];
        }

        return [
            'focus' => 'Balanced food-first support for exercise recovery and routine stability.',
            'foods' => ['salmon', 'leafy greens', 'oats', 'nuts'],
            'dishes' => ['Salmon with vegetables', 'Yogurt with oats and banana'],
            'note' => 'A balanced routine with nourishing meals may support energy and recovery.',
        ];
    }

    /**
     * @return array{
     *     focus:string,
     *     foods:list<string>,
     *     dishes:list<string>,
     *     note:string
     * }
     */
    private function normalizeNutritionSupport(mixed $value): array
    {
        if (!is_array($value)) {
            return $this->localNutritionSupport([]);
        }

        $focus = is_string($value['focus'] ?? null) ? trim($value['focus']) : '';
        $foods = array_slice($this->listValue($value['foods'] ?? null), 0, 5);
        $dishes = array_slice($this->listValue($value['dishes'] ?? null), 0, 4);
        $note = is_string($value['note'] ?? null) ? trim($value['note']) : '';
        $fallback = $this->localNutritionSupport([]);

        return [
            'focus' => $focus !== '' ? $focus : $fallback['focus'],
            'foods' => count($foods) >= 3 ? $foods : $fallback['foods'],
            'dishes' => count($dishes) >= 2 ? $dishes : $fallback['dishes'],
            'note' => $note !== '' ? $note : $fallback['note'],
        ];
    }

    /** @return list<string> */
    private function listValue(mixed $value): array
    {
        if (!is_array($value)) {
            return [];
        }

        return array_values(array_filter(
            array_map(static fn(mixed $item): string => is_string($item) ? trim($item) : '', $value),
            static fn(string $item): bool => $item !== '',
        ));
    }
}
